import type { Lang } from '../features/speech/speech'
import type { Side } from '../features/vision/distance'

// Every on-screen label and screen-reader name, in both languages. Spoken warnings stay in speech.ts.
// Screen-reader names say what a control does, not what it looks like.
const en = {
  appName: 'Second Sight',
  start: 'Start',
  stop: 'Stop',
  startLabel: 'Start Second Sight',
  stopLabel: 'Stop Second Sight',
  scan: 'Scan once',
  scanLabel: 'Scan once: hear everything in view',
  languageName: 'English',
  switchLanguage: 'Language: English. Switch to Telugu',
  settings: 'Settings',
  close: 'Close',
  status: {
    ready: 'Ready',
    watching: 'Watching',
    starting: 'Starting the camera',
    loading: 'Loading detection',
    cameraProblem: 'Camera did not start',
    modelMissing: 'Detection is not available',
    offline: 'Offline',
    online: 'Network on',
  },
  lane: { left: 'Left', ahead: 'Ahead', right: 'Right' } as Record<Side, string>,
  hazard: { left: 'Hazard on the left', ahead: 'Hazard ahead', right: 'Hazard on the right' } as Record<Side, string>,
  noHazard: 'Nothing detected',
  watchingHint: 'Watching. Double-tap the picture to scan.',
  wearTitle: 'Wear it at chest height',
  wearBody: 'Camera facing forward. Then press Start.',
  alert: {
    question: 'Are you OK?',
    helpIn: (n: number) => `Help message in ${n} seconds`,
    tapAnywhere: 'Tap anywhere if you are OK',
    cancelLabel: 'Tap anywhere if you are OK. This cancels the help message.',
    sending: 'Sending the help message',
    sent: 'Help message sent',
    failed: 'Could not send the help message',
    back: 'Back',
  },
  set: {
    title: 'Settings',
    languageGroup: 'Language and voice',
    language: 'Language',
    testVoice: 'Test the voice',
    testVoiceHint: 'Says one sentence in the chosen language.',
    installVoices: 'Install offline voices',
    installVoicesHint: 'Opens Android’s voice download screen. Needs Wi-Fi once.',
    installVoicesBrowser: 'Only needed in the Android app.',
    distanceGroup: 'Distance',
    calibrate: 'Calibrate distance',
    calibrateHint: 'Stand a person 5 metres away, point the camera at them, then press.',
    calibrateStopped: 'Start the camera first.',
    emergencyGroup: 'Emergency contact',
    number: 'Emergency phone number',
    testFall: 'Test the fall alert',
    testFallHint: 'Starts the 15 second countdown.',
    setupGroup: 'Setup',
    runSetup: 'Run setup again',
    advancedGroup: 'Advanced',
    advanced: 'Detector and speed',
    detector: 'Detector',
    detectorHint: 'For debugging. The app reloads when you change it.',
    fps: (n: number) => `${n} frames per second`,
    auto: 'Auto',
  },
  setup: {
    title: 'Set up Second Sight',
    languageStep: 'Choose your language',
    voiceStep: 'Install and test the voice',
    voiceBody: 'Download English (India) and Telugu, then come back and test.',
    installVoices: 'Install voices',
    browserNote: 'Voices are only installed in the Android app.',
    testVoice: 'Test the voice',
    numberStep: 'Add an emergency number',
    numberBody: 'Optional. This number gets a message with your location if a fall is detected.',
    number: 'Emergency phone number',
    done: 'Done',
    step: (n: number) => `Step ${n}`,
  },
}

type Strings = typeof en

const te: Strings = {
  appName: 'సెకండ్ సైట్',
  start: 'ప్రారంభించు',
  stop: 'ఆపు',
  startLabel: 'సెకండ్ సైట్ ప్రారంభించు',
  stopLabel: 'సెకండ్ సైట్ ఆపు',
  scan: 'ఒకసారి స్కాన్',
  scanLabel: 'ఒకసారి స్కాన్: ముందున్నవన్నీ వినండి',
  languageName: 'తెలుగు',
  switchLanguage: 'భాష: తెలుగు. ఇంగ్లీష్‌కు మార్చు',
  settings: 'సెట్టింగ్స్',
  close: 'మూసివేయి',
  status: {
    ready: 'సిద్ధం',
    watching: 'గమనిస్తోంది',
    starting: 'కెమెరా ప్రారంభమవుతోంది',
    loading: 'డిటెక్షన్ లోడ్ అవుతోంది',
    cameraProblem: 'కెమెరా ప్రారంభం కాలేదు',
    modelMissing: 'డిటెక్షన్ అందుబాటులో లేదు',
    offline: 'ఆఫ్‌లైన్',
    online: 'నెట్‌వర్క్ ఆన్',
  },
  lane: { left: 'ఎడమ', ahead: 'ముందు', right: 'కుడి' },
  hazard: { left: 'ఎడమవైపు అడ్డంకి', ahead: 'ముందు అడ్డంకి', right: 'కుడివైపు అడ్డంకి' },
  noHazard: 'ఏమీ కనిపించలేదు',
  watchingHint: 'గమనిస్తోంది. స్కాన్ కోసం చిత్రాన్ని రెండుసార్లు నొక్కండి.',
  wearTitle: 'ఛాతీ ఎత్తులో ధరించండి',
  wearBody: 'కెమెరా ముందుకు ఉండాలి. తర్వాత ప్రారంభించు నొక్కండి.',
  alert: {
    question: 'మీరు బాగున్నారా?',
    helpIn: n => `${n} సెకన్లలో సహాయ సందేశం`,
    tapAnywhere: 'బాగుంటే ఎక్కడైనా నొక్కండి',
    cancelLabel: 'బాగుంటే ఎక్కడైనా నొక్కండి. దీనితో సహాయ సందేశం రద్దవుతుంది.',
    sending: 'సహాయ సందేశం పంపుతోంది',
    sent: 'సహాయ సందేశం పంపబడింది',
    failed: 'సహాయ సందేశం పంపలేకపోయాం',
    back: 'వెనక్కి',
  },
  set: {
    title: 'సెట్టింగ్స్',
    languageGroup: 'భాష మరియు వాయిస్',
    language: 'భాష',
    testVoice: 'వాయిస్ పరీక్షించు',
    testVoiceHint: 'ఎంచుకున్న భాషలో ఒక వాక్యం చెబుతుంది.',
    installVoices: 'ఆఫ్‌లైన్ వాయిస్‌లు ఇన్‌స్టాల్ చేయి',
    installVoicesHint: 'ఆండ్రాయిడ్ వాయిస్ డౌన్‌లోడ్ స్క్రీన్ తెరుస్తుంది. ఒకసారి వై-ఫై కావాలి.',
    installVoicesBrowser: 'ఆండ్రాయిడ్ యాప్‌లో మాత్రమే అవసరం.',
    distanceGroup: 'దూరం',
    calibrate: 'దూరం కాలిబ్రేట్ చేయి',
    calibrateHint: 'ఒక వ్యక్తిని 5 మీటర్ల దూరంలో నిలబెట్టి, కెమెరా వారివైపు పెట్టి, నొక్కండి.',
    calibrateStopped: 'ముందు కెమెరా ప్రారంభించండి.',
    emergencyGroup: 'అత్యవసర కాంటాక్ట్',
    number: 'అత్యవసర ఫోన్ నంబర్',
    testFall: 'ఫాల్ అలర్ట్ పరీక్షించు',
    testFallHint: '15 సెకన్ల కౌంట్‌డౌన్ మొదలవుతుంది.',
    setupGroup: 'సెటప్',
    runSetup: 'సెటప్ మళ్ళీ చేయి',
    advancedGroup: 'అడ్వాన్స్‌డ్',
    advanced: 'డిటెక్టర్ మరియు వేగం',
    detector: 'డిటెక్టర్',
    detectorHint: 'డీబగ్గింగ్ కోసం. మార్చితే యాప్ రీలోడ్ అవుతుంది.',
    fps: n => `సెకనుకు ${n} ఫ్రేమ్‌లు`,
    auto: 'ఆటో',
  },
  setup: {
    title: 'సెకండ్ సైట్ సెటప్',
    languageStep: 'మీ భాష ఎంచుకోండి',
    voiceStep: 'వాయిస్ ఇన్‌స్టాల్ చేసి పరీక్షించండి',
    voiceBody: 'ఇంగ్లీష్ (ఇండియా) మరియు తెలుగు డౌన్‌లోడ్ చేసి, తిరిగి వచ్చి పరీక్షించండి.',
    installVoices: 'వాయిస్‌లు ఇన్‌స్టాల్ చేయి',
    browserNote: 'వాయిస్‌లు ఆండ్రాయిడ్ యాప్‌లో మాత్రమే ఇన్‌స్టాల్ అవుతాయి.',
    testVoice: 'వాయిస్ పరీక్షించు',
    numberStep: 'అత్యవసర నంబర్ జోడించండి',
    numberBody: 'ఐచ్ఛికం. పడిపోయినట్టు గుర్తిస్తే ఈ నంబర్‌కు మీ లొకేషన్‌తో సందేశం వెళ్తుంది.',
    number: 'అత్యవసర ఫోన్ నంబర్',
    done: 'పూర్తయింది',
    step: n => `దశ ${n}`,
  },
}

export const UI: Record<Lang, Strings> = { en, te }
// Each language's own name, for the control that switches to it.
export const LANGUAGE_NAME: Record<Lang, string> = { en: 'English', te: 'తెలుగు' }
