import type { Lang, SpeechRate } from '../features/speech/speech'
import type { Side } from '../features/vision/distance'

// Every on-screen label and screen-reader name, in both languages. Spoken warnings stay in speech.ts.
// Screen-reader names say what a control does, not what it looks like.
const en = {
  appName: 'Second Sight',
  start: 'Start',
  stop: 'Stop',
  startLabel: 'Start Second Sight',
  stopLabel: 'Stop Second Sight',
  scan: 'Scan once',
  scanLabel: 'Scan once: hear everything in view',
  languageName: 'English',
  switchLanguage: 'Language: English. Switch to Telugu',
  settings: 'Settings',
  close: 'Close',
  help: 'Help',
  helpLabel: 'Help: message and call my emergency contacts',
  status: {
    ready: 'Ready',
    watching: 'Watching',
    starting: 'Starting the camera',
    loading: 'Loading detection',
    cameraProblem: 'Camera did not start',
    modelMissing: 'Detection is not available',
    offline: 'Offline',
    online: 'Network on',
  },
  lane: { left: 'Left', ahead: 'Ahead', right: 'Right' } as Record<Side, string>,
  hazard: { left: 'Hazard on the left', ahead: 'Hazard ahead', right: 'Hazard on the right' } as Record<Side, string>,
  noHazard: 'Nothing detected',
  watchingHint: 'Watching. Double-tap the picture to scan.',
  wearTitle: 'Wear it at chest height',
  wearBody: 'Camera facing forward. Then press Start.',
  alert: {
    question: 'Are you OK?',
    helpQuestion: 'Asking for help',
    helpIn: (n: number) => `Message and calls in ${n} seconds`,
    tapAnywhere: 'Tap anywhere if you are OK',
    tapToCancel: 'Tap anywhere to cancel',
    cancelLabel: 'Tap anywhere if you are OK. This cancels the message and the calls.',
    cancelHelpLabel: 'Tap anywhere to cancel. Nobody will be messaged or called.',
    cancelSendingLabel: 'Tap anywhere to cancel. Nobody will be called.',
    sending: 'Sending the help message',
    sent: 'Help message sent',
    notSent: 'Could not send the help message',
    calling: (n: number, total: number) => `Calling contact ${n} of ${total}`,
    callingHint: 'The phone’s call screen opens for each call.',
    stopCalling: 'Stop calling',
    answered: 'Calls finished',
    nobody: 'Nobody answered',
    failed: 'Could not place a call',
    failedHint: 'Check the SIM card, the signal, and that a contact is saved.',
    alarmHint: 'The alarm is sounding so that people nearby can help.',
    stopAlarm: 'Stop the alarm',
    back: 'Back',
  },
  set: {
    title: 'Settings',
    languageGroup: 'Language and voice',
    language: 'Language',
    testVoice: 'Test the voice',
    testVoiceHint: 'Says one sentence in the chosen language.',
    installVoices: 'Install offline voices',
    installVoicesHint: 'Opens Android’s voice download screen. Needs Wi-Fi once.',
    installVoicesBrowser: 'Only needed in the Android app.',
    speed: 'Voice speed',
    speeds: { slow: 'Slow', normal: 'Normal', fast: 'Fast' } as Record<SpeechRate, string>,
    distanceGroup: 'Distance',
    calibrate: 'Calibrate distance',
    calibrateHint: 'Stand a person 5 metres away, point the camera at them, then press.',
    calibrateStopped: 'Start the camera first.',
    buzz: 'Feel the buzzes',
    buzzHint: 'Within two steps the phone buzzes. Left: one short. Right: one long. Ahead: two. Press to feel each.',
    emergencyGroup: 'Emergency contacts',
    contact: ['First contact', 'Second contact', 'Third contact'],
    contactsHint:
      'When help is needed, all get a message, then are called in this order. Leave a field empty to skip it.',
    siren: 'Alarm sound',
    sirenOn: 'On. If no contact can be reached, the phone sounds a loud alarm for people nearby.',
    sirenOff: 'Off. The phone stays quiet if no contact can be reached.',
    testFall: 'Test the fall alert',
    testFallHint: 'Starts the 15 second countdown, then messages and calls your contacts.',
    setupGroup: 'Setup',
    runSetup: 'Run setup again',
    shortcut: 'Volume-key shortcut',
    shortcutHint:
      'Hold both volume keys to open Second Sight with the camera on. Opens Android’s accessibility settings.',
    batteryGroup: 'Screen and battery',
    dim: 'Dim the screen while watching',
    dimOn: 'On. Saves battery. The screen stays on while the camera runs.',
    dimOff: 'Off. Full brightness while the camera runs.',
    torch: 'Torch in the dark',
    torchOn: 'On. The torch lights by itself when the camera finds it dark, and goes out when you stop.',
    torchOff: 'Off. The torch is never used.',
    advancedGroup: 'Advanced',
    advanced: 'Detector and speed',
    detector: 'Detector',
    detectorHint: 'For debugging. The app reloads when you change it.',
    fps: (n: number) => `${n} frames per second`,
    auto: 'Auto',
  },
  setup: {
    title: 'Set up Second Sight',
    languageStep: 'Choose your language',
    voiceStep: 'Install and test the voice',
    voiceBody: 'Download your language and English (India), then come back and test.',
    installVoices: 'Install voices',
    browserNote: 'Voices are only installed in the Android app.',
    testVoice: 'Test the voice',
    shortcutStep: 'Turn on the volume-key shortcut',
    shortcutBody:
      'Optional. Then holding both volume keys opens Second Sight with the camera on, even from the lock screen. On vivo and iQOO phones, first turn off Quick action → Flashlight.',
    openShortcut: 'Open accessibility settings',
    numberStep: 'Add an emergency contact',
    numberBody:
      'Optional. This number gets a message with your location, then a call, if a fall is detected or you ask for help. You can add two more in Settings.',
    number: 'First contact’s phone number',
    done: 'Done',
    step: (n: number) => `Step ${n}`,
  },
}

type Strings = typeof en

const te: Strings = {
  appName: 'సెకండ్ సైట్',
  start: 'ప్రారంభించు',
  stop: 'ఆపు',
  startLabel: 'సెకండ్ సైట్ ప్రారంభించు',
  stopLabel: 'సెకండ్ సైట్ ఆపు',
  scan: 'ఒకసారి స్కాన్',
  scanLabel: 'ఒకసారి స్కాన్: ముందున్నవన్నీ వినండి',
  languageName: 'తెలుగు',
  switchLanguage: 'భాష: తెలుగు. ఇంగ్లీష్‌కు మార్చు',
  settings: 'సెట్టింగ్స్',
  close: 'మూసివేయి',
  help: 'సహాయం',
  helpLabel: 'సహాయం: నా అత్యవసర కాంటాక్ట్‌లకు సందేశం పంపి, కాల్ చేయి',
  status: {
    ready: 'సిద్ధం',
    watching: 'గమనిస్తోంది',
    starting: 'కెమెరా ప్రారంభమవుతోంది',
    loading: 'డిటెక్షన్ లోడ్ అవుతోంది',
    cameraProblem: 'కెమెరా ప్రారంభం కాలేదు',
    modelMissing: 'డిటెక్షన్ అందుబాటులో లేదు',
    offline: 'ఆఫ్‌లైన్',
    online: 'నెట్‌వర్క్ ఆన్',
  },
  lane: { left: 'ఎడమ', ahead: 'ముందు', right: 'కుడి' },
  hazard: { left: 'ఎడమవైపు అడ్డంకి', ahead: 'ముందు అడ్డంకి', right: 'కుడివైపు అడ్డంకి' },
  noHazard: 'ఏమీ కనిపించలేదు',
  watchingHint: 'గమనిస్తోంది. స్కాన్ కోసం చిత్రాన్ని రెండుసార్లు నొక్కండి.',
  wearTitle: 'ఛాతీ ఎత్తులో ధరించండి',
  wearBody: 'కెమెరా ముందుకు ఉండాలి. తర్వాత ప్రారంభించు నొక్కండి.',
  alert: {
    question: 'మీరు బాగున్నారా?',
    helpQuestion: 'సహాయం అడుగుతోంది',
    helpIn: n => `${n} సెకన్లలో సందేశం, కాల్‌లు`,
    tapAnywhere: 'బాగుంటే ఎక్కడైనా నొక్కండి',
    tapToCancel: 'రద్దు చేయడానికి ఎక్కడైనా నొక్కండి',
    cancelLabel: 'బాగుంటే ఎక్కడైనా నొక్కండి. దీనితో సందేశం, కాల్‌లు రద్దవుతాయి.',
    cancelHelpLabel: 'రద్దు చేయడానికి ఎక్కడైనా నొక్కండి. ఎవరికీ సందేశం, కాల్ వెళ్ళవు.',
    cancelSendingLabel: 'రద్దు చేయడానికి ఎక్కడైనా నొక్కండి. ఎవరికీ కాల్ వెళ్ళదు.',
    sending: 'సహాయ సందేశం పంపుతోంది',
    sent: 'సహాయ సందేశం పంపబడింది',
    notSent: 'సహాయ సందేశం పంపలేకపోయాం',
    calling: (n, total) => `${total} లో ${n}వ కాంటాక్ట్‌కు కాల్ చేస్తున్నాం`,
    callingHint: 'ప్రతి కాల్‌కు ఫోన్ కాల్ స్క్రీన్ తెరుచుకుంటుంది.',
    stopCalling: 'కాల్ చేయడం ఆపు',
    answered: 'కాల్‌లు ముగిశాయి',
    nobody: 'ఎవరూ సమాధానం ఇవ్వలేదు',
    failed: 'కాల్ చేయలేకపోయాం',
    failedHint: 'సిమ్ కార్డ్, సిగ్నల్, మరియు కాంటాక్ట్ సేవ్ అయిందో లేదో చూడండి.',
    alarmHint: 'దగ్గరలో ఉన్నవారు సహాయం చేయడానికి అలారం మోగుతోంది.',
    stopAlarm: 'అలారం ఆపు',
    back: 'వెనక్కి',
  },
  set: {
    title: 'సెట్టింగ్స్',
    languageGroup: 'భాష మరియు వాయిస్',
    language: 'భాష',
    testVoice: 'వాయిస్ పరీక్షించు',
    testVoiceHint: 'ఎంచుకున్న భాషలో ఒక వాక్యం చెబుతుంది.',
    installVoices: 'ఆఫ్‌లైన్ వాయిస్‌లు ఇన్‌స్టాల్ చేయి',
    installVoicesHint: 'ఆండ్రాయిడ్ వాయిస్ డౌన్‌లోడ్ స్క్రీన్ తెరుస్తుంది. ఒకసారి వై-ఫై కావాలి.',
    installVoicesBrowser: 'ఆండ్రాయిడ్ యాప్‌లో మాత్రమే అవసరం.',
    speed: 'వాయిస్ వేగం',
    speeds: { slow: 'నెమ్మదిగా', normal: 'సాధారణం', fast: 'వేగంగా' },
    distanceGroup: 'దూరం',
    calibrate: 'దూరం కాలిబ్రేట్ చేయి',
    calibrateHint: 'ఒక వ్యక్తిని 5 మీటర్ల దూరంలో నిలబెట్టి, కెమెరా వారివైపు పెట్టి, నొక్కండి.',
    calibrateStopped: 'ముందు కెమెరా ప్రారంభించండి.',
    buzz: 'వైబ్రేషన్‌లను తెలుసుకోండి',
    buzzHint:
      'రెండు అడుగుల లోపు ఫోన్ వైబ్రేట్ అవుతుంది. ఎడమ: ఒక చిన్నది. కుడి: ఒక పొడవైనది. ముందు: రెండు. ఒక్కొక్కటి తెలుసుకోవడానికి నొక్కండి.',
    emergencyGroup: 'అత్యవసర కాంటాక్ట్‌లు',
    contact: ['మొదటి కాంటాక్ట్', 'రెండవ కాంటాక్ట్', 'మూడవ కాంటాక్ట్'],
    contactsHint: 'సహాయం అవసరమైనప్పుడు అందరికీ సందేశం పంపి, ఈ క్రమంలో కాల్ చేస్తాం. వద్దనుకున్న చోట ఖాళీగా వదిలేయండి.',
    siren: 'అలారం శబ్దం',
    sirenOn: 'ఆన్. ఏ కాంటాక్ట్ దొరకకపోతే, దగ్గరలో ఉన్నవారి కోసం ఫోన్ గట్టిగా అలారం మోగిస్తుంది.',
    sirenOff: 'ఆఫ్. ఏ కాంటాక్ట్ దొరకకపోయినా ఫోన్ నిశ్శబ్దంగా ఉంటుంది.',
    testFall: 'ఫాల్ అలర్ట్ పరీక్షించు',
    testFallHint: '15 సెకన్ల కౌంట్‌డౌన్ మొదలై, తర్వాత మీ కాంటాక్ట్‌లకు సందేశం, కాల్ వెళ్తాయి.',
    setupGroup: 'సెటప్',
    runSetup: 'సెటప్ మళ్ళీ చేయి',
    shortcut: 'వాల్యూమ్ కీ షార్ట్‌కట్',
    shortcutHint:
      'రెండు వాల్యూమ్ కీలు నొక్కి పట్టుకుంటే కెమెరా ఆన్‌తో సెకండ్ సైట్ తెరుచుకుంటుంది. ఆండ్రాయిడ్ యాక్సెసిబిలిటీ సెట్టింగ్స్ తెరుస్తుంది.',
    batteryGroup: 'స్క్రీన్ మరియు బ్యాటరీ',
    dim: 'చూస్తున్నప్పుడు స్క్రీన్ తగ్గించు',
    dimOn: 'ఆన్. బ్యాటరీ ఆదా. కెమెరా నడుస్తున్నంత సేపు స్క్రీన్ ఆన్‌లో ఉంటుంది.',
    dimOff: 'ఆఫ్. కెమెరా నడుస్తున్నప్పుడు పూర్తి వెలుగు.',
    torch: 'చీకటిలో టార్చ్',
    torchOn: 'ఆన్. కెమెరాకు చీకటిగా ఉంటే టార్చ్ దానంతట అదే వెలుగుతుంది, ఆపినప్పుడు ఆరిపోతుంది.',
    torchOff: 'ఆఫ్. టార్చ్ ఎప్పుడూ వాడబడదు.',
    advancedGroup: 'అడ్వాన్స్‌డ్',
    advanced: 'డిటెక్టర్ మరియు వేగం',
    detector: 'డిటెక్టర్',
    detectorHint: 'డీబగ్గింగ్ కోసం. మార్చితే యాప్ రీలోడ్ అవుతుంది.',
    fps: n => `సెకనుకు ${n} ఫ్రేమ్‌లు`,
    auto: 'ఆటో',
  },
  setup: {
    title: 'సెకండ్ సైట్ సెటప్',
    languageStep: 'మీ భాష ఎంచుకోండి',
    voiceStep: 'వాయిస్ ఇన్‌స్టాల్ చేసి పరీక్షించండి',
    voiceBody: 'మీ భాష మరియు ఇంగ్లీష్ (ఇండియా) డౌన్‌లోడ్ చేసి, తిరిగి వచ్చి పరీక్షించండి.',
    installVoices: 'వాయిస్‌లు ఇన్‌స్టాల్ చేయి',
    browserNote: 'వాయిస్‌లు ఆండ్రాయిడ్ యాప్‌లో మాత్రమే ఇన్‌స్టాల్ అవుతాయి.',
    testVoice: 'వాయిస్ పరీక్షించు',
    shortcutStep: 'వాల్యూమ్ కీ షార్ట్‌కట్ ఆన్ చేయండి',
    shortcutBody:
      'ఐచ్ఛికం. తర్వాత రెండు వాల్యూమ్ కీలు నొక్కి పట్టుకుంటే, లాక్ స్క్రీన్ నుండి కూడా, కెమెరా ఆన్‌తో సెకండ్ సైట్ తెరుచుకుంటుంది. వివో, iQOO ఫోన్లలో ముందుగా Quick action → Flashlight ఆఫ్ చేయండి.',
    openShortcut: 'యాక్సెసిబిలిటీ సెట్టింగ్స్ తెరువు',
    numberStep: 'అత్యవసర కాంటాక్ట్ జోడించండి',
    numberBody:
      'ఐచ్ఛికం. పడిపోయినట్టు గుర్తిస్తే లేదా మీరు సహాయం అడిగితే ఈ నంబర్‌కు మీ లొకేషన్‌తో సందేశం, తర్వాత కాల్ వెళ్తాయి. సెట్టింగ్స్‌లో ఇంకా రెండు జోడించవచ్చు.',
    number: 'మొదటి కాంటాక్ట్ ఫోన్ నంబర్',
    done: 'పూర్తయింది',
    step: n => `దశ ${n}`,
  },
}

// Hindi, Tamil and Kannada speak in their own language; their screen labels are English until translated.
export const UI: Record<Lang, Strings> = { en, te, hi: en, ta: en, kn: en }
// Each language's own name, for the control that switches to it.
export const LANGUAGE_NAME: Record<Lang, string> = {
  en: 'English',
  te: 'తెలుగు',
  hi: 'हिन्दी',
  ta: 'தமிழ்',
  kn: 'ಕನ್ನಡ',
}
